ARDUINO_DIR 	= /usr/share/arduino
BOARD_TAG    	= atmega328
#BOARD_TAG    	= uno
ARDUINO_PORT 	= /dev/ttyUSB*
ARDUINO_LIBS 	+=TimerOne
ARDUINO_LIBS 	+=Wire
ARDUINO_LIBS 	+=SPI
ARDUINO_LIBS 	+=TFT
include /usr/share/arduino/Arduino.mk